### ISSUE TITLE
An exception raised during on_startup events prevents the application to start

### ISSUE THREAD

**Issue by cecton** [big-data-europe/mu-swarm-logger-service#11]
Here the database was not ready:

```
swarm-logger_1        | Traceback (most recent call last):
swarm-logger_1        |   File "/src/run.py", line 5, in <module>
swarm-logger_1        |     runpy.run_module('muswarmlogger')
swarm-logger_1        |   File "/usr/local/lib/python3.6/runpy.py", line 208, in run_module
swarm-logger_1        |     return _run_code(code, {}, init_globals, run_name, mod_spec)
swarm-logger_1        |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
swarm-logger_1        |     exec(code, run_globals)
swarm-logger_1        |   File "/src/muswarmlogger/__main__.py", line 36, in <module>
swarm-logger_1        |     main()
swarm-logger_1        |   File "/src/muswarmlogger/__main__.py", line 29, in main
swarm-logger_1        |     sparql_endpoint=opt.sparql_endpoint, debug=opt.debug))
swarm-logger_1        |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
swarm-logger_1        |     return future.result()
swarm-logger_1        |   File "/src/muswarmlogger/loop.py", line 19, in run_loop
swarm-logger_1        |     await run_on_startup_subroutines(docker, sparql)
swarm-logger_1        |   File "/src/muswarmlogger/events.py", line 88, in run_on_startup_subroutines
swarm-logger_1        |     await subroutine(docker, sparql)
swarm-logger_1        |   File "/src/muswarmlogger/loggers/sparql.py", line 288, in start_logging_existing_containers
swarm-logger_1        |     containers = await docker.containers()
swarm-logger_1        |   File "/usr/local/lib/python3.6/site-packages/aiodockerpy/api/client.py", line 215, in _result
swarm-logger_1        |     async with async_response as response:
swarm-logger_1        |   File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 626, in __aenter__
swarm-logger_1        |     self._resp = yield from self._coro
swarm-logger_1        |   File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 235, in _request
swarm-logger_1        |     yield from resp.start(conn, read_until_eof)
swarm-logger_1        |   File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 535, in start
swarm-logger_1        |     self._continue = None
swarm-logger_1        |   File "/usr/local/lib/python3.6/site-packages/aiohttp/helpers.py", line 695, in __exit__
swarm-logger_1        |     raise asyncio.TimeoutError from None
swarm-logger_1        | concurrent.futures._base.TimeoutError
mubdelogging_swarm-logger_1 exited with code 1
```

@fr0gs that was the error you noticed the other day right?

**Comment by cecton** [comment]
Solved by #12
